name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (opzionale ma raccomandato per build più complessi)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image and tag it as 'latest'
      - name: Build the Docker image
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/frontend-react:latest
          echo "Building image with tag: $IMAGE_TAG"
          docker build . --file DockerfileFrontend --tag $IMAGE_TAG
          echo "Image built successfully with tag: $IMAGE_TAG"

      # Step 5: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/frontend-react:latest
          echo "Pushing image with tag: $IMAGE_TAG"
          docker push $IMAGE_TAG
