name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx (opzionale ma raccomandato per build più complessi)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . --file DockerfileFrontend --tag ${{ secrets.DOCKER_USERNAME }}/frontend-react:$(date +%s)

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-react:$(date +%s)

    # Optional: Tag the image as 'latest'
    - name: Tag image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend-react:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/frontend-react:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-react:latest
